GOOGLE_API_KEY = "AIzaSyAPFFdem2Wn9A6GePvqnEcFr5eLbZIq0-Q"  
SUPABASE_URL = "https://ogyowawmivvjuwncxojh.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9neW93YXdtaXZ2anV3bmN4b2poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxNDA1NzYsImV4cCI6MjA4MTcxNjU3Nn0.s0_uXRbqwAjR_JrYOhr6dm8XIImRgGEW8FoHbeDajFk"
